"""initial schema

Revision ID: 240b0ad2f12f
Revises: 
Create Date: 2026-04-02 21:46:48.818489+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "240b0ad2f12f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("oidc_sub", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("oidc_sub"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("ssh_key", sa.Text(), nullable=True),
        sa.Column("vault_kv_path", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_credentials_id"), "credentials", ["id"], unique=False)
    op.create_table(
        "distros",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("end_of_life_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_distros_id"), "distros", ["id"], unique=False)
    op.create_index(op.f("ix_distros_name"), "distros", ["name"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=True)
    op.create_table(
        "command_execution_policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_memory_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_cpu_time_ms", sa.Integer(), nullable=True),
        sa.Column("max_disk_io_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_network_io_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_open_files", sa.Integer(), nullable=True),
        sa.Column("max_processes", sa.Integer(), nullable=True),
        sa.Column("allow_sudo", sa.Boolean(), nullable=False),
        sa.Column("allow_network_access", sa.Boolean(), nullable=False),
        sa.Column("allow_file_system_write", sa.Boolean(), nullable=False),
        sa.Column("require_validation", sa.Boolean(), nullable=False),
        sa.Column("max_retry_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_delay_seconds", sa.Integer(), nullable=False),
        sa.Column("log_stdout", sa.Boolean(), nullable=False),
        sa.Column("log_stderr", sa.Boolean(), nullable=False),
        sa.Column("monitor_resources", sa.Boolean(), nullable=False),
        sa.Column("applies_to_all_systems", sa.Boolean(), nullable=False),
        sa.Column("applies_to_all_users", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_execution_policies_id"),
        "command_execution_policies",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_command_execution_policies_name"),
        "command_execution_policies",
        ["name"],
        unique=True,
    )
    op.create_table(
        "command_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template", sa.String(length=1000), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.String(length=50), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_templates_id"), "command_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_command_templates_name"), "command_templates", ["name"], unique=False
    )
    op.create_table(
        "command_validation_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("validation_type", sa.String(length=50), nullable=False),
        sa.Column("pattern", sa.String(length=1000), nullable=False),
        sa.Column("is_regex", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_validation_rules_id"),
        "command_validation_rules",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_command_validation_rules_name"),
        "command_validation_rules",
        ["name"],
        unique=False,
    )
    op.create_table(
        "command_whitelist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("command_pattern", sa.String(length=500), nullable=False),
        sa.Column("is_regex", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("risk_level", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("requires_sudo", sa.Boolean(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_whitelist_id"), "command_whitelist", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_command_whitelist_name"), "command_whitelist", ["name"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_table(
        "ssh_security_policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("max_auth_tries", sa.Integer(), nullable=True),
        sa.Column("connection_timeout", sa.Integer(), nullable=True),
        sa.Column("idle_timeout", sa.Integer(), nullable=True),
        sa.Column("require_host_key_verification", sa.Boolean(), nullable=True),
        sa.Column("minimum_key_size", sa.Integer(), nullable=True),
        sa.Column("allowed_auth_methods", sa.String(length=255), nullable=True),
        sa.Column("allowed_ciphers", sa.String(length=255), nullable=True),
        sa.Column("allowed_macs", sa.String(length=255), nullable=True),
        sa.Column("allowed_kex", sa.String(length=255), nullable=True),
        sa.Column("log_commands", sa.Boolean(), nullable=True),
        sa.Column("log_file_transfers", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_ssh_security_policies_id"),
        "ssh_security_policies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "vault_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("server_url", sa.String(length=255), nullable=True),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(), nullable=True),
        sa.Column("health_status", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vault_config_id"), "vault_config", ["id"], unique=False)
    op.create_table(
        "command_distro_mapping",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("command_id", sa.Integer(), nullable=False),
        sa.Column("distro_id", sa.Integer(), nullable=False),
        sa.Column("distro_version_pattern", sa.String(length=100), nullable=True),
        sa.Column("command_override", sa.String(length=500), nullable=True),
        sa.Column("is_supported", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["command_whitelist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["distro_id"],
            ["distros.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_distro_mapping_id"),
        "command_distro_mapping",
        ["id"],
        unique=False,
    )
    op.create_table(
        "command_execution_user_policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timeout_override", sa.Integer(), nullable=True),
        sa.Column("memory_limit_override", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["command_execution_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_execution_user_policies_id"),
        "command_execution_user_policies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "command_template_distros",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("distro_id", sa.Integer(), nullable=False),
        sa.Column("distro_version_pattern", sa.String(length=100), nullable=True),
        sa.Column("template_override", sa.String(length=1000), nullable=True),
        sa.Column("is_supported", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["distro_id"],
            ["distros.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["command_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_template_distros_id"),
        "command_template_distros",
        ["id"],
        unique=False,
    )
    op.create_table(
        "systems",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=False),
        sa.Column("distro_id", sa.Integer(), nullable=False),
        sa.Column("os_version", sa.String(length=50), nullable=False),
        sa.Column("last_audited", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("credentials_id", sa.Integer(), nullable=False),
        sa.Column("ssh_security_policy_id", sa.Integer(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=True),
        sa.Column("registered_by", sa.Integer(), nullable=True),
        sa.Column("update_policy", sa.String(length=50), nullable=True),
        sa.Column("last_successful_update", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["credentials_id"],
            ["credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["distro_id"],
            ["distros.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registered_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ssh_security_policy_id"],
            ["ssh_security_policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_systems_distro_id"), "systems", ["distro_id"], unique=False
    )
    op.create_index(op.f("ix_systems_hostname"), "systems", ["hostname"], unique=True)
    op.create_index(op.f("ix_systems_id"), "systems", ["id"], unique=False)
    op.create_index(
        op.f("ix_systems_os_version"), "systems", ["os_version"], unique=False
    )
    op.create_table(
        "command_execution_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("metric_date", sa.DateTime(), nullable=False),
        sa.Column("metric_hour", sa.Integer(), nullable=False),
        sa.Column("total_executions", sa.Integer(), nullable=False),
        sa.Column("successful_executions", sa.Integer(), nullable=False),
        sa.Column("failed_executions", sa.Integer(), nullable=False),
        sa.Column("timeout_executions", sa.Integer(), nullable=False),
        sa.Column("avg_execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("max_execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("min_execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("avg_memory_usage_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_memory_usage_bytes", sa.BigInteger(), nullable=True),
        sa.Column("total_cpu_time_ms", sa.BigInteger(), nullable=True),
        sa.Column("validation_failures", sa.Integer(), nullable=False),
        sa.Column("high_risk_executions", sa.Integer(), nullable=False),
        sa.Column("sudo_executions", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_execution_metrics_id"),
        "command_execution_metrics",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_command_execution_metrics_metric_date"),
        "command_execution_metrics",
        ["metric_date"],
        unique=False,
    )
    op.create_table(
        "command_execution_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("normalized_command", sa.Text(), nullable=True),
        sa.Column("command_hash", sa.String(length=64), nullable=False),
        sa.Column("execution_status", sa.String(length=50), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_memory_usage_bytes", sa.BigInteger(), nullable=True),
        sa.Column("cpu_time_ms", sa.Integer(), nullable=True),
        sa.Column("disk_io_bytes", sa.BigInteger(), nullable=True),
        sa.Column("network_io_bytes", sa.BigInteger(), nullable=True),
        sa.Column("validation_status", sa.String(length=50), nullable=False),
        sa.Column("risk_level", sa.String(length=50), nullable=False),
        sa.Column("requires_sudo", sa.Boolean(), nullable=False),
        sa.Column("actual_user", sa.String(length=100), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("execution_context", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_execution_results_command_hash"),
        "command_execution_results",
        ["command_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_command_execution_results_id"),
        "command_execution_results",
        ["id"],
        unique=False,
    )
    op.create_table(
        "command_execution_system_policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("timeout_override", sa.Integer(), nullable=True),
        sa.Column("memory_limit_override", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["command_execution_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_execution_system_policies_id"),
        "command_execution_system_policies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "command_validation_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("command_id", sa.Integer(), nullable=True),
        sa.Column("validation_rule_id", sa.Integer(), nullable=True),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("raw_command", sa.String(length=1000), nullable=False),
        sa.Column("normalized_command", sa.String(length=1000), nullable=True),
        sa.Column("validation_status", sa.String(length=50), nullable=False),
        sa.Column("validation_reason", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["command_whitelist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validation_rule_id"],
            ["command_validation_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_validation_logs_id"),
        "command_validation_logs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("schedule", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.Column("next_run", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("installed_version", sa.String(length=50), nullable=False),
        sa.Column("installation_date", sa.DateTime(), nullable=True),
        sa.Column("package_type", sa.String(length=50), nullable=True),
        sa.Column("is_security_critical", sa.Boolean(), nullable=True),
        sa.Column("last_audited", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_packages_id"), "packages", ["id"], unique=False)
    op.create_index(op.f("ix_packages_name"), "packages", ["name"], unique=False)
    op.create_table(
        "ssh_host_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("key_type", sa.String(length=50), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=255), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ssh_host_keys_id"), "ssh_host_keys", ["id"], unique=False)
    op.create_table(
        "ssh_security_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_details", sa.Text(), nullable=True),
        sa.Column("source_ip", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ssh_security_logs_id"), "ssh_security_logs", ["id"], unique=False
    )
    op.create_table(
        "system_audits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("audit_type", sa.String(length=50), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_audits_id"), "system_audits", ["id"], unique=False)
    op.create_table(
        "system_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("cpu_arch", sa.String(length=50), nullable=True),
        sa.Column("cpu_cores", sa.Integer(), nullable=True),
        sa.Column("memory_total", sa.BigInteger(), nullable=True),
        sa.Column("disk_total", sa.BigInteger(), nullable=True),
        sa.Column("environment_type", sa.String(length=50), nullable=True),
        sa.Column("maintenance_window", sa.String(length=100), nullable=True),
        sa.Column("owner_contact", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=True),
        sa.Column("last_connection", sa.DateTime(), nullable=True),
        sa.Column("connection_status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_id"),
    )
    op.create_index(
        op.f("ix_system_metadata_id"), "system_metadata", ["id"], unique=False
    )
    op.create_table(
        "command_execution_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("execution_result_id", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_result_id"],
            ["command_execution_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_execution_queue_id"),
        "command_execution_queue",
        ["id"],
        unique=False,
    )
    op.create_table(
        "command_resource_limits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execution_result_id", sa.Integer(), nullable=False),
        sa.Column("max_memory_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_cpu_time_ms", sa.Integer(), nullable=True),
        sa.Column("max_disk_io_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_network_io_bytes", sa.BigInteger(), nullable=True),
        sa.Column("max_open_files", sa.Integer(), nullable=True),
        sa.Column("max_processes", sa.Integer(), nullable=True),
        sa.Column("memory_limit_exceeded", sa.Boolean(), nullable=False),
        sa.Column("cpu_limit_exceeded", sa.Boolean(), nullable=False),
        sa.Column("disk_io_limit_exceeded", sa.Boolean(), nullable=False),
        sa.Column("network_io_limit_exceeded", sa.Boolean(), nullable=False),
        sa.Column("limit_source", sa.String(length=100), nullable=False),
        sa.Column("policy_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_result_id"],
            ["command_execution_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_command_resource_limits_id"),
        "command_resource_limits",
        ["id"],
        unique=False,
    )
    op.create_table(
        "job_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_history_id"), "job_history", ["id"], unique=False)
    op.create_table(
        "package_updates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("available_version", sa.String(length=50), nullable=False),
        sa.Column("update_type", sa.String(length=50), nullable=False),
        sa.Column("discovered_on", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_package_updates_id"), "package_updates", ["id"], unique=False
    )
    op.create_table(
        "package_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("old_version", sa.String(length=50), nullable=True),
        sa.Column("new_version", sa.String(length=50), nullable=True),
        sa.Column("performed_at", sa.DateTime(), nullable=False),
        sa.Column("performed_by", sa.Integer(), nullable=True),
        sa.Column("job_history_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_history_id"],
            ["job_history.id"],
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performed_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_package_history_id"), "package_history", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_package_history_id"), table_name="package_history")
    op.drop_table("package_history")
    op.drop_index(op.f("ix_package_updates_id"), table_name="package_updates")
    op.drop_table("package_updates")
    op.drop_index(op.f("ix_job_history_id"), table_name="job_history")
    op.drop_table("job_history")
    op.drop_index(
        op.f("ix_command_resource_limits_id"), table_name="command_resource_limits"
    )
    op.drop_table("command_resource_limits")
    op.drop_index(
        op.f("ix_command_execution_queue_id"), table_name="command_execution_queue"
    )
    op.drop_table("command_execution_queue")
    op.drop_index(op.f("ix_system_metadata_id"), table_name="system_metadata")
    op.drop_table("system_metadata")
    op.drop_index(op.f("ix_system_audits_id"), table_name="system_audits")
    op.drop_table("system_audits")
    op.drop_index(op.f("ix_ssh_security_logs_id"), table_name="ssh_security_logs")
    op.drop_table("ssh_security_logs")
    op.drop_index(op.f("ix_ssh_host_keys_id"), table_name="ssh_host_keys")
    op.drop_table("ssh_host_keys")
    op.drop_index(op.f("ix_packages_name"), table_name="packages")
    op.drop_index(op.f("ix_packages_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        op.f("ix_command_validation_logs_id"), table_name="command_validation_logs"
    )
    op.drop_table("command_validation_logs")
    op.drop_index(
        op.f("ix_command_execution_system_policies_id"),
        table_name="command_execution_system_policies",
    )
    op.drop_table("command_execution_system_policies")
    op.drop_index(
        op.f("ix_command_execution_results_id"), table_name="command_execution_results"
    )
    op.drop_index(
        op.f("ix_command_execution_results_command_hash"),
        table_name="command_execution_results",
    )
    op.drop_table("command_execution_results")
    op.drop_index(
        op.f("ix_command_execution_metrics_metric_date"),
        table_name="command_execution_metrics",
    )
    op.drop_index(
        op.f("ix_command_execution_metrics_id"), table_name="command_execution_metrics"
    )
    op.drop_table("command_execution_metrics")
    op.drop_index(op.f("ix_systems_os_version"), table_name="systems")
    op.drop_index(op.f("ix_systems_id"), table_name="systems")
    op.drop_index(op.f("ix_systems_hostname"), table_name="systems")
    op.drop_index(op.f("ix_systems_distro_id"), table_name="systems")
    op.drop_table("systems")
    op.drop_index(
        op.f("ix_command_template_distros_id"), table_name="command_template_distros"
    )
    op.drop_table("command_template_distros")
    op.drop_index(
        op.f("ix_command_execution_user_policies_id"),
        table_name="command_execution_user_policies",
    )
    op.drop_table("command_execution_user_policies")
    op.drop_index(
        op.f("ix_command_distro_mapping_id"), table_name="command_distro_mapping"
    )
    op.drop_table("command_distro_mapping")
    op.drop_index(op.f("ix_vault_config_id"), table_name="vault_config")
    op.drop_table("vault_config")
    op.drop_table("user_role")
    op.drop_index(
        op.f("ix_ssh_security_policies_id"), table_name="ssh_security_policies"
    )
    op.drop_table("ssh_security_policies")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_command_whitelist_name"), table_name="command_whitelist")
    op.drop_index(op.f("ix_command_whitelist_id"), table_name="command_whitelist")
    op.drop_table("command_whitelist")
    op.drop_index(
        op.f("ix_command_validation_rules_name"), table_name="command_validation_rules"
    )
    op.drop_index(
        op.f("ix_command_validation_rules_id"), table_name="command_validation_rules"
    )
    op.drop_table("command_validation_rules")
    op.drop_index(op.f("ix_command_templates_name"), table_name="command_templates")
    op.drop_index(op.f("ix_command_templates_id"), table_name="command_templates")
    op.drop_table("command_templates")
    op.drop_index(
        op.f("ix_command_execution_policies_name"),
        table_name="command_execution_policies",
    )
    op.drop_index(
        op.f("ix_command_execution_policies_id"),
        table_name="command_execution_policies",
    )
    op.drop_table("command_execution_policies")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_distros_name"), table_name="distros")
    op.drop_index(op.f("ix_distros_id"), table_name="distros")
    op.drop_table("distros")
    op.drop_index(op.f("ix_credentials_id"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
